### ISSUE TITLE
Release lobanov/rubocop 

### ISSUE THREAD

**Issue by spajic** [spajic/lobanov#44]
We have some rubocop to not forget `lobanov!` (at 3commas)

Also it has some bugs

Probably we can separate it, and fix a bug in autocorrect (and use in 3commas as a gem)

**Comment by spajic** [comment]
```
t.kovalev@MacBook-Pro-Timofei-Kovalev-RW7X4WR7JL 3commas % bin/cop -a
Inspecting 36 files
...........................C

Offenses:

spec/controllers/accounts/positions_controller_spec.rb:162:5: C: [Corrected] Commas/LobanovWithBang: Do not forget to change from 'lobanov!' to 'lobanov'.
    it 'schedules update', :lobanov! do ...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

27 files inspected, 1 offense detected, 1 offense corrected
Infinite loop detected in /Users/t.kovalev/works/3commas/spec/controllers/accounts/positions_controller_spec.rb and caused by Commas/LobanovWithBang
/Users/t.kovalev/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/rubocop-1.59.0/lib/rubocop/runner.rb:332:in `check_for_infinite_loop'
/Users/t.kovalev/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/rubocop-1.59.0/lib/rubocop/runner.rb:315:in `block in iterate_until_no_changes'
```
